### PR TITLE
docs: remove erroneous Google reference

### PR DESCRIPTION
**Pull request by jeff-d**
Signed-off-by: Jeff Deininger <9385180+jeff-d@users.noreply.github.com>

### CODE REVIEW

**Review by jeff-d — COMMENTED** [review]
I have read the Mondoo CLA Document and I hereby sign the CLA

**Review by jeff-d — COMMENTED** [review]
recheck

**Review by tas50 — APPROVED** [review]

**Comment by chris-rock** [comment]
recheck

**Comment by jeff-d** [comment]
I have read the Mondoo CLA Document and I hereby sign the CLA

**Pull request merged**
